Repository plansoft-it/GestioneCompetenze, pull requests merged in 2020-12, with the labels that each got.

#10 1 homepage
  index.html
  style.css
Labels: enhancement

#11 3 modifica competenze
  addEmployee.html
  addSkill.html
  edit.js
  modifica.html
Labels: enhancement

#8 4 ricerca
  SearchFilteredUser.html
  filterUsers.js
  style.css
Labels: enhancement

#9 2 lista competenze
  ShowAllUserPage.html
  showCompetences.js
  styles.css
Labels: enhancement

#24 16 Inizializzazione progetto
  .gitignore
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/plansoft/gestionecompetenze/GestionecompetenzeApplication.java
  src/main/resources/application.properties
  src/test/java/plansoft/gestionecompetenze/GestionecompetenzeApplicationTests.java
Labels: back-end

#26 22 area
  src/main/java/plansoft/skillsmanagement/SkillsmanagementApplication.java
  src/main/java/plansoft/skillsmanagement/area/Area.java
  src/main/java/plansoft/skillsmanagement/area/AreaController.java
  src/main/java/plansoft/skillsmanagement/area/AreaRepository.java
  src/main/java/plansoft/skillsmanagement/area/AreaService.java
Labels: back-end, enhancement

#30 29 Modifica al gitignore: si ignorano i log
  .gitignore
Labels: back-end, invalid

#25 15 Realizzazione entità Dipendente
  src/main/java/plansoft/skillsmanagement/SkillsManagementApplication.java
  src/main/java/plansoft/skillsmanagement/employee/Employee.java
  src/main/java/plansoft/skillsmanagement/employee/EmployeeController.java
  src/main/java/plansoft/skillsmanagement/employee/EmployeeRepository.java
  src/main/java/plansoft/skillsmanagement/employee/EmployeeService.java
  src/main/resources/application.properties
Labels: back-end, enhancement

#32 13 Creazione entità Competenza
  src/main/java/plansoft/skillsmanagement/skill/Skill.java
  src/main/java/plansoft/skillsmanagement/skill/SkillController.java
  src/main/java/plansoft/skillsmanagement/skill/SkillRepository.java
  src/main/java/plansoft/skillsmanagement/skill/SkillService.java
Labels: back-end, enhancement

#31 14 Realizzazione entità Level
  src/main/java/plansoft/skillsmanagement/level/Level.java
  src/main/java/plansoft/skillsmanagement/level/LevelController.java
  src/main/java/plansoft/skillsmanagement/level/LevelRepository.java
  src/main/java/plansoft/skillsmanagement/level/LevelService.java
Labels: back-end, enhancement

#27 12 documentazione frontend
  README.md
Labels: documentation

#34 33 Correzione del tipo del campo id Employee completata
  src/main/java/plansoft/skillsmanagement/employee/Employee.java
  src/main/java/plansoft/skillsmanagement/employee/EmployeeController.java
  src/main/java/plansoft/skillsmanagement/employee/EmployeeRepository.java
  src/main/java/plansoft/skillsmanagement/employee/EmployeeService.java
Labels: back-end, invalid

#37 35 order level
  src/main/java/plansoft/skillsmanagement/level/Level.java
  src/main/java/plansoft/skillsmanagement/level/LevelRepository.java
  src/main/java/plansoft/skillsmanagement/level/LevelService.java
Labels: back-end, enhancement

#38 23 Realizzazione dell'entità SkillEmp
  src/main/java/plansoft/skillsmanagement/skillemployee/SkillEmployee.java
  src/main/java/plansoft/skillsmanagement/skillemployee/SkillEmployeeController.java
  src/main/java/plansoft/skillsmanagement/skillemployee/SkillEmployeeRepository.java
  src/main/java/plansoft/skillsmanagement/skillemployee/SkillEmployeeService.java
Labels: back-end, enhancement
