Repository plansoft-it/GestioneCompetenze, pull requests merged in 2021-01, with the labels that each got.

#40 36 Autoincrement Id
  src/main/java/plansoft/skillsmanagement/area/Area.java
  src/main/java/plansoft/skillsmanagement/area/AreaService.java
  src/main/java/plansoft/skillsmanagement/employee/Employee.java
  src/main/java/plansoft/skillsmanagement/employee/EmployeeService.java
  src/main/java/plansoft/skillsmanagement/level/Level.java
  src/main/java/plansoft/skillsmanagement/level/LevelService.java
  src/main/java/plansoft/skillsmanagement/skill/Skill.java
  src/main/java/plansoft/skillsmanagement/skill/SkillService.java
  src/main/java/plansoft/skillsmanagement/skillemployee/SkillEmployee.java
  src/main/java/plansoft/skillsmanagement/skillemployee/SkillEmployeeController.java
  src/main/java/plansoft/skillsmanagement/skillemployee/SkillEmployeeService.java
Labels: back-end, enhancement

#39 18 scrittura angular
  .gitignore
  angular.json
  karma.conf.js
  package.json
  src/main/webapp/app/app-routing.module.ts
  src/main/webapp/app/app.component.css
  src/main/webapp/app/app.component.html
  src/main/webapp/app/app.component.spec.ts
  src/main/webapp/app/app.component.ts
  src/main/webapp/app/app.module.ts
  src/main/webapp/app/area.ts
  src/main/webapp/app/employee-editor/employee-editor.component.css
  src/main/webapp/app/employee-editor/employee-editor.component.html
  src/main/webapp/app/employee-editor/employee-editor.component.spec.ts
  src/main/webapp/app/employee-editor/employee-editor.component.ts
  src/main/webapp/app/employee.ts
  src/main/webapp/app/level.ts
  src/main/webapp/app/mock-area.ts
  src/main/webapp/app/mock-employee.ts
  src/main/webapp/app/mock-level.ts
  src/main/webapp/app/mock-skill.ts
  src/main/webapp/app/mock-skillEmp.ts
  src/main/webapp/app/skill-editor/skill-editor.component.css
  src/main/webapp/app/skill-editor/skill-editor.component.html
  src/main/webapp/app/skill-editor/skill-editor.component.spec.ts
  src/main/webapp/app/skill-editor/skill-editor.component.ts
  src/main/webapp/app/skill.ts
  src/main/webapp/app/skillEmp.ts
  src/main/webapp/assets/.gitkeep
  src/main/webapp/environments/environment.prod.ts
  src/main/webapp/environments/environment.ts
  src/main/webapp/favicon.ico
  src/main/webapp/index.html
  src/main/webapp/main.ts
  src/main/webapp/polyfills.ts
  src/main/webapp/styles.css
  src/main/webapp/test.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.spec.json
  tslint.json
Labels: enhancement, front-end

#42 28 Documentazione backend
  documentazione backend gestione competenze.pdf
Labels: back-end, documentation
